/* ============================================================================
   01 - SNOWFLAKE FOUNDATION
   Roles, compute, database, medallion schemas, CSV file format, RAW tables.
   Medallion: RAW (as-landed) -> STG (clean) -> MART (star) + REJECT (quarantine)
   ============================================================================ */

-- ---------- Least-privilege service account for ADF ingestion ----------
USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS ADF_INGEST_ROLE
  COMMENT = 'Least-privilege role used by Azure Data Factory for RAW loads';

CREATE USER IF NOT EXISTS ADF_SVC
  PASSWORD = '<SET_A_STRONG_PASSWORD>'
  DEFAULT_ROLE = ADF_INGEST_ROLE
  DEFAULT_WAREHOUSE = WH_INGEST
  MUST_CHANGE_PASSWORD = FALSE
  COMMENT = 'Service account for ADF ingestion';

GRANT ROLE ADF_INGEST_ROLE TO USER ADF_SVC;
GRANT ROLE ADF_INGEST_ROLE TO ROLE SYSADMIN;

-- ---------- Compute (aggressive auto-suspend for cost control) ----------
USE ROLE SYSADMIN;
CREATE WAREHOUSE IF NOT EXISTS WH_INGEST
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Compute for ingestion and transforms';

-- ---------- Database + medallion schemas ----------
CREATE DATABASE IF NOT EXISTS SUPPLY_CHAIN;
USE DATABASE SUPPLY_CHAIN;
CREATE SCHEMA IF NOT EXISTS RAW     COMMENT = 'As-landed, all VARCHAR';
CREATE SCHEMA IF NOT EXISTS STG     COMMENT = 'Cleaned, typed, deduped';
CREATE SCHEMA IF NOT EXISTS MART    COMMENT = 'Star schema for Power BI';
CREATE SCHEMA IF NOT EXISTS REJECT  COMMENT = 'Quarantined bad rows';

-- ---------- CSV file format (keep mess intact for STG to clean) ----------
CREATE OR REPLACE FILE FORMAT RAW.FF_CSV
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  EMPTY_FIELD_AS_NULL = TRUE
  TRIM_SPACE = FALSE;

-- ---------- RAW tables (all VARCHAR = faithful landing) ----------
CREATE OR REPLACE TABLE RAW.DIM_CUSTOMER (
  CUSTOMER_KEY VARCHAR, CUSTOMER_NAME VARCHAR, SEGMENT VARCHAR,
  COUNTRY VARCHAR, REGION VARCHAR );

CREATE OR REPLACE TABLE RAW.DIM_DATE (
  DATE_KEY VARCHAR, FULL_DATE VARCHAR, YEAR VARCHAR, QUARTER VARCHAR,
  MONTH_NUM VARCHAR, MONTH_NAME VARCHAR, MONTH_YEAR VARCHAR,
  WEEK_OF_YEAR VARCHAR, DAY_OF_MONTH VARCHAR, DAY_NAME VARCHAR, IS_WEEKEND VARCHAR );

CREATE OR REPLACE TABLE RAW.DIM_PRODUCT (
  PRODUCT_KEY VARCHAR, SKU VARCHAR, PRODUCT_NAME VARCHAR, CATEGORY VARCHAR,
  ABC_CLASS VARCHAR, PRIMARY_SUPPLIER_KEY VARCHAR, UNIT_COST VARCHAR, UNIT_PRICE VARCHAR );

CREATE OR REPLACE TABLE RAW.DIM_SHIP_MODE (
  SHIP_MODE_KEY VARCHAR, SHIP_MODE VARCHAR, AVG_TRANSIT_DAYS VARCHAR, COST_FACTOR VARCHAR );

CREATE OR REPLACE TABLE RAW.DIM_SUPPLIER (
  SUPPLIER_KEY VARCHAR, SUPPLIER_NAME VARCHAR, COUNTRY VARCHAR, REGION VARCHAR,
  RELIABILITY_TIER VARCHAR, BASE_LEAD_TIME_DAYS VARCHAR, TARGET_OTIF VARCHAR );

CREATE OR REPLACE TABLE RAW.DIM_WAREHOUSE (
  WAREHOUSE_KEY VARCHAR, WAREHOUSE_NAME VARCHAR, CITY VARCHAR,
  COUNTRY VARCHAR, REGION VARCHAR );

CREATE OR REPLACE TABLE RAW.FACT_INVENTORY (
  PRODUCT_KEY VARCHAR, WAREHOUSE_KEY VARCHAR, ON_HAND_QTY VARCHAR,
  REORDER_POINT VARCHAR, SAFETY_STOCK VARCHAR, SNAPSHOT_DATE VARCHAR );

CREATE OR REPLACE TABLE RAW.FACT_PURCHASE_ORDERS (
  PO_ID VARCHAR, SUPPLIER_KEY VARCHAR, PRODUCT_KEY VARCHAR, WAREHOUSE_KEY VARCHAR,
  ORDER_QTY VARCHAR, RECEIVED_QTY VARCHAR, UNIT_COST VARCHAR, PO_AMOUNT VARCHAR,
  ORDER_DATE VARCHAR, PROMISED_DATE VARCHAR, RECEIVED_DATE VARCHAR );

CREATE OR REPLACE TABLE RAW.FACT_SALES_ORDERS (
  SO_ID VARCHAR, CUSTOMER_KEY VARCHAR, PRODUCT_KEY VARCHAR, WAREHOUSE_KEY VARCHAR,
  SHIP_MODE_KEY VARCHAR, ORDER_QTY VARCHAR, SHIPPED_QTY VARCHAR, FREIGHT_COST VARCHAR,
  REVENUE VARCHAR, ORDER_DATE VARCHAR, SHIP_DATE VARCHAR, PROMISED_DATE VARCHAR,
  DELIVERY_DATE VARCHAR );

-- ---------- Grant the service role exactly what ADF needs ----------
USE ROLE SECURITYADMIN;
GRANT USAGE ON WAREHOUSE WH_INGEST              TO ROLE ADF_INGEST_ROLE;
GRANT USAGE ON DATABASE  SUPPLY_CHAIN           TO ROLE ADF_INGEST_ROLE;
GRANT USAGE ON SCHEMA    SUPPLY_CHAIN.RAW       TO ROLE ADF_INGEST_ROLE;
GRANT INSERT, SELECT, TRUNCATE ON ALL TABLES    IN SCHEMA SUPPLY_CHAIN.RAW TO ROLE ADF_INGEST_ROLE;
GRANT INSERT, SELECT, TRUNCATE ON FUTURE TABLES IN SCHEMA SUPPLY_CHAIN.RAW TO ROLE ADF_INGEST_ROLE;
-- ADF's staged COPY creates a transient stage + file format at load time:
GRANT CREATE STAGE       ON SCHEMA SUPPLY_CHAIN.RAW TO ROLE ADF_INGEST_ROLE;
GRANT CREATE FILE FORMAT ON SCHEMA SUPPLY_CHAIN.RAW TO ROLE ADF_INGEST_ROLE;

USE ROLE SYSADMIN;
SHOW TABLES IN SCHEMA SUPPLY_CHAIN.RAW;   -- expect 9 empty tables
