/* ============================================================================
   PHASE 4 - STG CLEANING LAYER
   RAW (all VARCHAR, as-landed)  ->  STG (clean, typed, deduped, conformed)
   Bad/invalid rows are QUARANTINED to the REJECT schema with a reason, never
   silently dropped. Dimensions are built first so facts can validate their
   foreign keys against the conformed dims.
   ============================================================================ */

USE ROLE SYSADMIN;
USE WAREHOUSE WH_INGEST;
USE DATABASE SUPPLY_CHAIN;

/* ============================================================================
   1. DIMENSIONS  (clean + type + dedup)
   ============================================================================ */

-- ---- DIM_SUPPLIER : trim/case, fix 'Gemany' typo, 'N/A'/'' -> NULL, dedup ----
CREATE OR REPLACE TABLE STG.DIM_SUPPLIER AS
SELECT
    TRIM(SUPPLIER_KEY)                                   AS SUPPLIER_KEY,
    INITCAP(TRIM(SUPPLIER_NAME))                         AS SUPPLIER_NAME,
    CASE
        WHEN TRIM(COUNTRY) IN ('', 'N/A')      THEN NULL
        WHEN UPPER(TRIM(COUNTRY)) = 'GEMANY'   THEN 'Germany'
        ELSE INITCAP(TRIM(COUNTRY))
    END                                                  AS COUNTRY,
    UPPER(TRIM(REGION))                                  AS REGION,
    UPPER(TRIM(RELIABILITY_TIER))                        AS RELIABILITY_TIER,
    TRY_TO_NUMBER(TRIM(BASE_LEAD_TIME_DAYS))             AS BASE_LEAD_TIME_DAYS,
    TRY_TO_DECIMAL(TRIM(TARGET_OTIF), 5, 3)              AS TARGET_OTIF
FROM RAW.DIM_SUPPLIER
QUALIFY ROW_NUMBER() OVER (PARTITION BY TRIM(SUPPLIER_KEY) ORDER BY SUPPLIER_NAME) = 1;

-- ---- DIM_PRODUCT : category standardise, strip $/commas, orphan supplier->NULL ----
CREATE OR REPLACE TABLE STG.DIM_PRODUCT AS
SELECT
    TRIM(p.PRODUCT_KEY)                                  AS PRODUCT_KEY,
    TRIM(p.SKU)                                          AS SKU,
    INITCAP(TRIM(p.PRODUCT_NAME))                        AS PRODUCT_NAME,
    CASE
        WHEN UPPER(TRIM(p.CATEGORY)) IN ('BEARING','BEARINGS') THEN 'Bearings'
        ELSE INITCAP(TRIM(p.CATEGORY))
    END                                                  AS CATEGORY,
    COALESCE(NULLIF(UPPER(TRIM(p.ABC_CLASS)), ''), 'C')  AS ABC_CLASS,
    s.SUPPLIER_KEY                                       AS PRIMARY_SUPPLIER_KEY,  -- NULL if orphan
    TRY_TO_DECIMAL(REPLACE(REPLACE(p.UNIT_COST,'$',''),',',''), 18, 2)  AS UNIT_COST,
    TRY_TO_DECIMAL(REPLACE(REPLACE(p.UNIT_PRICE,'$',''),',',''),18, 2)  AS UNIT_PRICE
FROM RAW.DIM_PRODUCT p
LEFT JOIN STG.DIM_SUPPLIER s
       ON TRIM(p.PRIMARY_SUPPLIER_KEY) = s.SUPPLIER_KEY
QUALIFY ROW_NUMBER() OVER (PARTITION BY TRIM(p.PRODUCT_KEY) ORDER BY p.SKU) = 1;

-- ---- DIM_CUSTOMER : segment standardise, blank name -> 'Unknown', dedup ----
CREATE OR REPLACE TABLE STG.DIM_CUSTOMER AS
SELECT
    TRIM(CUSTOMER_KEY)                                   AS CUSTOMER_KEY,
    COALESCE(NULLIF(TRIM(CUSTOMER_NAME), ''), 'Unknown') AS CUSTOMER_NAME,
    CASE UPPER(TRIM(REPLACE(SEGMENT, '.', '')))
        WHEN 'OEM'        THEN 'OEM'
        WHEN 'WHOLESALE'  THEN 'Wholesale'
        WHEN 'RETAIL'     THEN 'Retail'
        WHEN 'GOVT'       THEN 'Government'
        WHEN 'GOVERNMENT' THEN 'Government'
        ELSE INITCAP(TRIM(SEGMENT))
    END                                                  AS SEGMENT,
    INITCAP(TRIM(COUNTRY))                               AS COUNTRY,
    UPPER(TRIM(REGION))                                  AS REGION
FROM RAW.DIM_CUSTOMER
QUALIFY ROW_NUMBER() OVER (PARTITION BY TRIM(CUSTOMER_KEY) ORDER BY CUSTOMER_NAME) = 1;

-- ---- DIM_WAREHOUSE : trim/case city & country, dedup ----
CREATE OR REPLACE TABLE STG.DIM_WAREHOUSE AS
SELECT
    TRIM(WAREHOUSE_KEY)                                  AS WAREHOUSE_KEY,
    TRIM(WAREHOUSE_NAME)                                 AS WAREHOUSE_NAME,
    INITCAP(TRIM(CITY))                                  AS CITY,
    INITCAP(TRIM(COUNTRY))                               AS COUNTRY,
    UPPER(TRIM(REGION))                                  AS REGION
FROM RAW.DIM_WAREHOUSE
QUALIFY ROW_NUMBER() OVER (PARTITION BY TRIM(WAREHOUSE_KEY) ORDER BY WAREHOUSE_NAME) = 1;

-- ---- DIM_SHIP_MODE : already clean, just type ----
CREATE OR REPLACE TABLE STG.DIM_SHIP_MODE AS
SELECT
    TRIM(SHIP_MODE_KEY)                                  AS SHIP_MODE_KEY,
    TRIM(SHIP_MODE)                                      AS SHIP_MODE,
    TRY_TO_NUMBER(AVG_TRANSIT_DAYS)                      AS AVG_TRANSIT_DAYS,
    TRY_TO_DECIMAL(COST_FACTOR, 10, 2)                   AS COST_FACTOR
FROM RAW.DIM_SHIP_MODE
QUALIFY ROW_NUMBER() OVER (PARTITION BY TRIM(SHIP_MODE_KEY) ORDER BY SHIP_MODE) = 1;

-- ---- DIM_DATE : type cast the generated calendar ----
CREATE OR REPLACE TABLE STG.DIM_DATE AS
SELECT
    TRY_TO_NUMBER(DATE_KEY)                              AS DATE_KEY,
    TRY_TO_DATE(LEFT(TRIM(FULL_DATE), 10), 'YYYY-MM-DD') AS FULL_DATE,
    TRY_TO_NUMBER(YEAR)                                  AS YEAR,
    TRIM(QUARTER)                                        AS QUARTER,
    TRY_TO_NUMBER(MONTH_NUM)                             AS MONTH_NUM,
    TRIM(MONTH_NAME)                                     AS MONTH_NAME,
    TRIM(MONTH_YEAR)                                     AS MONTH_YEAR,
    TRY_TO_NUMBER(WEEK_OF_YEAR)                          AS WEEK_OF_YEAR,
    TRY_TO_NUMBER(DAY_OF_MONTH)                          AS DAY_OF_MONTH,
    TRIM(DAY_NAME)                                       AS DAY_NAME,
    TO_BOOLEAN(IS_WEEKEND)                               AS IS_WEEKEND
FROM RAW.DIM_DATE
QUALIFY ROW_NUMBER() OVER (PARTITION BY DATE_KEY ORDER BY DATE_KEY) = 1;


/* ============================================================================
   2. FACTS  (clean + type + multi-format date parse + validate + quarantine)
   Pattern per fact:
     a) _PREP transient table = cleaned/typed columns + REJECT_REASON
     b) STG.<fact>     = valid rows (reason IS NULL), deduped, with date keys
     c) REJECT.<fact>  = invalid rows (reason IS NOT NULL), deduped
   ============================================================================ */

-- Reusable note: dates land as mixed strings, so we COALESCE TRY_TO_DATE over
-- every format we saw (ISO, US, DD-MON-YYYY, slash-ISO). Unparseable -> NULL.

-- ----------------------------- PURCHASE ORDERS -----------------------------
CREATE OR REPLACE TRANSIENT TABLE STG._PREP_PO AS
WITH base AS (
    SELECT
        TRIM(PO_ID)         AS PO_ID,
        TRIM(SUPPLIER_KEY)  AS SUPPLIER_KEY,
        TRIM(PRODUCT_KEY)   AS PRODUCT_KEY,
        TRIM(WAREHOUSE_KEY) AS WAREHOUSE_KEY,
        TRY_TO_NUMBER(REPLACE(REPLACE(ORDER_QTY,'$',''),',',''))           AS ORDER_QTY,
        TRY_TO_NUMBER(REPLACE(REPLACE(RECEIVED_QTY,'$',''),',',''))        AS RECEIVED_QTY,
        TRY_TO_DECIMAL(REPLACE(REPLACE(UNIT_COST,'$',''),',',''),18,2)     AS UNIT_COST,
        TRY_TO_DECIMAL(REPLACE(REPLACE(PO_AMOUNT,'$',''),',',''),18,2)     AS PO_AMOUNT,
        COALESCE(TRY_TO_DATE(ORDER_DATE,'YYYY-MM-DD'),TRY_TO_DATE(ORDER_DATE,'MM/DD/YYYY'),
                 TRY_TO_DATE(ORDER_DATE,'DD-MON-YYYY'),TRY_TO_DATE(ORDER_DATE,'YYYY/MM/DD'))   AS ORDER_DATE,
        COALESCE(TRY_TO_DATE(PROMISED_DATE,'YYYY-MM-DD'),TRY_TO_DATE(PROMISED_DATE,'MM/DD/YYYY'),
                 TRY_TO_DATE(PROMISED_DATE,'DD-MON-YYYY'),TRY_TO_DATE(PROMISED_DATE,'YYYY/MM/DD')) AS PROMISED_DATE,
        COALESCE(TRY_TO_DATE(RECEIVED_DATE,'YYYY-MM-DD'),TRY_TO_DATE(RECEIVED_DATE,'MM/DD/YYYY'),
                 TRY_TO_DATE(RECEIVED_DATE,'DD-MON-YYYY'),TRY_TO_DATE(RECEIVED_DATE,'YYYY/MM/DD')) AS RECEIVED_DATE
    FROM RAW.FACT_PURCHASE_ORDERS
),
joined AS (
    SELECT b.*,
           s.SUPPLIER_KEY AS S_MATCH,
           p.PRODUCT_KEY  AS P_MATCH
    FROM base b
    LEFT JOIN STG.DIM_SUPPLIER s ON b.SUPPLIER_KEY = s.SUPPLIER_KEY
    LEFT JOIN STG.DIM_PRODUCT  p ON b.PRODUCT_KEY  = p.PRODUCT_KEY
)
SELECT
    PO_ID, SUPPLIER_KEY, PRODUCT_KEY, WAREHOUSE_KEY,
    ORDER_QTY, RECEIVED_QTY, UNIT_COST, PO_AMOUNT,
    ORDER_DATE, PROMISED_DATE, RECEIVED_DATE,
    NULLIF(ARRAY_TO_STRING(ARRAY_CONSTRUCT_COMPACT(
        IFF(ORDER_QTY IS NULL OR ORDER_QTY <= 0,                                   'BAD_ORDER_QTY', NULL),
        IFF(RECEIVED_QTY IS NOT NULL AND ORDER_QTY IS NOT NULL AND RECEIVED_QTY > ORDER_QTY,
                                                                                  'RECEIVED_GT_ORDERED', NULL),
        IFF(S_MATCH IS NULL,                                                       'ORPHAN_SUPPLIER', NULL),
        IFF(P_MATCH IS NULL,                                                       'ORPHAN_PRODUCT', NULL)
    ), '; '), '') AS REJECT_REASON
FROM joined;

CREATE OR REPLACE TABLE STG.FACT_PURCHASE_ORDERS AS
SELECT
    PO_ID, SUPPLIER_KEY, PRODUCT_KEY, WAREHOUSE_KEY,
    ORDER_QTY, RECEIVED_QTY, UNIT_COST,
    COALESCE(PO_AMOUNT, ORDER_QTY * UNIT_COST)           AS PO_AMOUNT,
    ORDER_DATE, PROMISED_DATE, RECEIVED_DATE,
    TRY_TO_NUMBER(TO_CHAR(ORDER_DATE,'YYYYMMDD'))        AS ORDER_DATE_KEY,
    TRY_TO_NUMBER(TO_CHAR(PROMISED_DATE,'YYYYMMDD'))     AS PROMISED_DATE_KEY,
    TRY_TO_NUMBER(TO_CHAR(RECEIVED_DATE,'YYYYMMDD'))     AS RECEIVED_DATE_KEY
FROM STG._PREP_PO
WHERE REJECT_REASON IS NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY PO_ID ORDER BY ORDER_DATE NULLS LAST) = 1;

CREATE OR REPLACE TABLE REJECT.FACT_PURCHASE_ORDERS AS
SELECT *, CURRENT_TIMESTAMP() AS REJECTED_AT
FROM STG._PREP_PO
WHERE REJECT_REASON IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY PO_ID ORDER BY ORDER_DATE NULLS LAST) = 1;

DROP TABLE STG._PREP_PO;

-- ------------------------------- SALES ORDERS ------------------------------
CREATE OR REPLACE TRANSIENT TABLE STG._PREP_SO AS
WITH base AS (
    SELECT
        TRIM(SO_ID)         AS SO_ID,
        TRIM(CUSTOMER_KEY)  AS CUSTOMER_KEY,
        TRIM(PRODUCT_KEY)   AS PRODUCT_KEY,
        TRIM(WAREHOUSE_KEY) AS WAREHOUSE_KEY,
        TRIM(SHIP_MODE_KEY) AS SHIP_MODE_KEY,
        TRY_TO_NUMBER(REPLACE(REPLACE(ORDER_QTY,'$',''),',',''))           AS ORDER_QTY,
        TRY_TO_NUMBER(REPLACE(REPLACE(SHIPPED_QTY,'$',''),',',''))         AS SHIPPED_QTY,
        TRY_TO_DECIMAL(REPLACE(REPLACE(FREIGHT_COST,'$',''),',',''),18,2)  AS FREIGHT_COST,
        TRY_TO_DECIMAL(REPLACE(REPLACE(REVENUE,'$',''),',',''),18,2)       AS REVENUE,
        COALESCE(TRY_TO_DATE(ORDER_DATE,'YYYY-MM-DD'),TRY_TO_DATE(ORDER_DATE,'MM/DD/YYYY'),
                 TRY_TO_DATE(ORDER_DATE,'DD-MON-YYYY'),TRY_TO_DATE(ORDER_DATE,'YYYY/MM/DD'))   AS ORDER_DATE,
        COALESCE(TRY_TO_DATE(SHIP_DATE,'YYYY-MM-DD'),TRY_TO_DATE(SHIP_DATE,'MM/DD/YYYY'),
                 TRY_TO_DATE(SHIP_DATE,'DD-MON-YYYY'),TRY_TO_DATE(SHIP_DATE,'YYYY/MM/DD'))      AS SHIP_DATE,
        COALESCE(TRY_TO_DATE(PROMISED_DATE,'YYYY-MM-DD'),TRY_TO_DATE(PROMISED_DATE,'MM/DD/YYYY'),
                 TRY_TO_DATE(PROMISED_DATE,'DD-MON-YYYY'),TRY_TO_DATE(PROMISED_DATE,'YYYY/MM/DD')) AS PROMISED_DATE,
        COALESCE(TRY_TO_DATE(DELIVERY_DATE,'YYYY-MM-DD'),TRY_TO_DATE(DELIVERY_DATE,'MM/DD/YYYY'),
                 TRY_TO_DATE(DELIVERY_DATE,'DD-MON-YYYY'),TRY_TO_DATE(DELIVERY_DATE,'YYYY/MM/DD')) AS DELIVERY_DATE
    FROM RAW.FACT_SALES_ORDERS
),
joined AS (
    SELECT b.*,
           c.CUSTOMER_KEY  AS C_MATCH,
           sm.SHIP_MODE_KEY AS SM_MATCH
    FROM base b
    LEFT JOIN STG.DIM_CUSTOMER  c  ON b.CUSTOMER_KEY  = c.CUSTOMER_KEY
    LEFT JOIN STG.DIM_SHIP_MODE sm ON b.SHIP_MODE_KEY = sm.SHIP_MODE_KEY
)
SELECT
    SO_ID, CUSTOMER_KEY, PRODUCT_KEY, WAREHOUSE_KEY, SHIP_MODE_KEY,
    ORDER_QTY, SHIPPED_QTY, FREIGHT_COST, REVENUE,
    ORDER_DATE, SHIP_DATE, PROMISED_DATE, DELIVERY_DATE,
    NULLIF(ARRAY_TO_STRING(ARRAY_CONSTRUCT_COMPACT(
        IFF(ORDER_QTY IS NULL OR ORDER_QTY <= 0,                                   'BAD_ORDER_QTY', NULL),
        IFF(SHIPPED_QTY IS NOT NULL AND (SHIPPED_QTY < 0 OR
            (ORDER_QTY IS NOT NULL AND SHIPPED_QTY > ORDER_QTY)),                   'SHIPPED_INVALID', NULL),
        IFF(FREIGHT_COST IS NOT NULL AND FREIGHT_COST < 0,                          'NEG_FREIGHT', NULL),
        IFF(C_MATCH IS NULL,                                                        'ORPHAN_CUSTOMER', NULL),
        IFF(SM_MATCH IS NULL,                                                       'ORPHAN_SHIPMODE', NULL)
    ), '; '), '') AS REJECT_REASON
FROM joined;

CREATE OR REPLACE TABLE STG.FACT_SALES_ORDERS AS
SELECT
    SO_ID, CUSTOMER_KEY, PRODUCT_KEY, WAREHOUSE_KEY, SHIP_MODE_KEY,
    ORDER_QTY, SHIPPED_QTY, FREIGHT_COST, REVENUE,
    ORDER_DATE, SHIP_DATE, PROMISED_DATE, DELIVERY_DATE,
    TRY_TO_NUMBER(TO_CHAR(ORDER_DATE,'YYYYMMDD'))        AS ORDER_DATE_KEY,
    TRY_TO_NUMBER(TO_CHAR(SHIP_DATE,'YYYYMMDD'))         AS SHIP_DATE_KEY,
    TRY_TO_NUMBER(TO_CHAR(PROMISED_DATE,'YYYYMMDD'))     AS PROMISED_DATE_KEY,
    TRY_TO_NUMBER(TO_CHAR(DELIVERY_DATE,'YYYYMMDD'))     AS DELIVERY_DATE_KEY
FROM STG._PREP_SO
WHERE REJECT_REASON IS NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY SO_ID ORDER BY ORDER_DATE NULLS LAST) = 1;

CREATE OR REPLACE TABLE REJECT.FACT_SALES_ORDERS AS
SELECT *, CURRENT_TIMESTAMP() AS REJECTED_AT
FROM STG._PREP_SO
WHERE REJECT_REASON IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY SO_ID ORDER BY ORDER_DATE NULLS LAST) = 1;

DROP TABLE STG._PREP_SO;

-- -------------------------------- INVENTORY --------------------------------
CREATE OR REPLACE TRANSIENT TABLE STG._PREP_INV AS
WITH base AS (
    SELECT
        TRIM(PRODUCT_KEY)   AS PRODUCT_KEY,
        TRIM(WAREHOUSE_KEY) AS WAREHOUSE_KEY,
        TRY_TO_NUMBER(REPLACE(REPLACE(ON_HAND_QTY,'$',''),',',''))    AS ON_HAND_QTY,
        TRY_TO_NUMBER(REPLACE(REPLACE(REORDER_POINT,'$',''),',',''))  AS REORDER_POINT,
        TRY_TO_NUMBER(REPLACE(REPLACE(SAFETY_STOCK,'$',''),',',''))   AS SAFETY_STOCK,
        COALESCE(TRY_TO_DATE(SNAPSHOT_DATE,'YYYY-MM-DD'),TRY_TO_DATE(SNAPSHOT_DATE,'MM/DD/YYYY'),
                 TRY_TO_DATE(SNAPSHOT_DATE,'DD-MON-YYYY'),TRY_TO_DATE(SNAPSHOT_DATE,'YYYY/MM/DD')) AS SNAPSHOT_DATE
    FROM RAW.FACT_INVENTORY
),
joined AS (
    SELECT b.*, p.PRODUCT_KEY AS P_MATCH
    FROM base b
    LEFT JOIN STG.DIM_PRODUCT p ON b.PRODUCT_KEY = p.PRODUCT_KEY
)
SELECT
    PRODUCT_KEY, WAREHOUSE_KEY, ON_HAND_QTY, REORDER_POINT, SAFETY_STOCK, SNAPSHOT_DATE,
    NULLIF(ARRAY_TO_STRING(ARRAY_CONSTRUCT_COMPACT(
        IFF(ON_HAND_QTY IS NULL OR ON_HAND_QTY < 0,  'BAD_ON_HAND', NULL),   -- 0 is valid (stockout)
        IFF(SNAPSHOT_DATE IS NULL,                   'BAD_SNAPSHOT_DATE', NULL),
        IFF(P_MATCH IS NULL,                         'ORPHAN_PRODUCT', NULL)
    ), '; '), '') AS REJECT_REASON
FROM joined;

CREATE OR REPLACE TABLE STG.FACT_INVENTORY AS
SELECT
    PRODUCT_KEY, WAREHOUSE_KEY, ON_HAND_QTY, REORDER_POINT, SAFETY_STOCK, SNAPSHOT_DATE,
    TRY_TO_NUMBER(TO_CHAR(SNAPSHOT_DATE,'YYYYMMDD'))     AS SNAPSHOT_DATE_KEY
FROM STG._PREP_INV
WHERE REJECT_REASON IS NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY PRODUCT_KEY, WAREHOUSE_KEY, SNAPSHOT_DATE ORDER BY ON_HAND_QTY) = 1;

CREATE OR REPLACE TABLE REJECT.FACT_INVENTORY AS
SELECT *, CURRENT_TIMESTAMP() AS REJECTED_AT
FROM STG._PREP_INV
WHERE REJECT_REASON IS NOT NULL;

DROP TABLE STG._PREP_INV;


/* ============================================================================
   3. VERIFICATION
   ============================================================================ */

-- 3a. STG row counts (these feed the dashboard)
SELECT 'STG.DIM_SUPPLIER'         obj, COUNT(*) n FROM STG.DIM_SUPPLIER
UNION ALL SELECT 'STG.DIM_PRODUCT',         COUNT(*) FROM STG.DIM_PRODUCT
UNION ALL SELECT 'STG.DIM_CUSTOMER',        COUNT(*) FROM STG.DIM_CUSTOMER
UNION ALL SELECT 'STG.DIM_WAREHOUSE',       COUNT(*) FROM STG.DIM_WAREHOUSE
UNION ALL SELECT 'STG.DIM_SHIP_MODE',       COUNT(*) FROM STG.DIM_SHIP_MODE
UNION ALL SELECT 'STG.DIM_DATE',            COUNT(*) FROM STG.DIM_DATE
UNION ALL SELECT 'STG.FACT_PURCHASE_ORDERS',COUNT(*) FROM STG.FACT_PURCHASE_ORDERS
UNION ALL SELECT 'STG.FACT_SALES_ORDERS',   COUNT(*) FROM STG.FACT_SALES_ORDERS
UNION ALL SELECT 'STG.FACT_INVENTORY',      COUNT(*) FROM STG.FACT_INVENTORY
ORDER BY 1;

-- 3b. What did we quarantine, and why?
SELECT 'PURCHASE_ORDERS' fact, REJECT_REASON, COUNT(*) n FROM REJECT.FACT_PURCHASE_ORDERS GROUP BY ALL
UNION ALL
SELECT 'SALES_ORDERS', REJECT_REASON, COUNT(*) FROM REJECT.FACT_SALES_ORDERS GROUP BY ALL
UNION ALL
SELECT 'INVENTORY', REJECT_REASON, COUNT(*) FROM REJECT.FACT_INVENTORY GROUP BY ALL
ORDER BY 1, 3 DESC;

-- 3c. Proof the cleaning worked: no dirty artifacts remain in STG
SELECT 'orphan supplier keys in product' chk, COUNT(*) n
FROM STG.DIM_PRODUCT WHERE PRIMARY_SUPPLIER_KEY IS NULL          -- expect 3 (set to NULL)
UNION ALL
SELECT 'distinct supplier countries', COUNT(DISTINCT COUNTRY) FROM STG.DIM_SUPPLIER
UNION ALL
SELECT 'distinct product categories', COUNT(DISTINCT CATEGORY) FROM STG.DIM_PRODUCT  -- expect 8
UNION ALL
SELECT 'distinct customer segments', COUNT(DISTINCT SEGMENT) FROM STG.DIM_CUSTOMER   -- expect 4
UNION ALL
SELECT 'PO rows with unparsed order_date', COUNT(*) FROM STG.FACT_PURCHASE_ORDERS WHERE ORDER_DATE IS NULL;
